### ISSUE TITLE
protocol missing in some urls

### ISSUE THREAD

**Issue by luv2code** [firesidefiction/firesidefiction.github.io#4]
for instance in index.html, these two urls are missing the`http://`
```html
  <link rel="canonical" href="firesidefiction.com/">
  <link type="application/atom+xml" rel="alternate" href="firesidefiction.com/feed.xml" title="Fireside Magazine" />
```
and in `feed.xml`, the links are missing the protocol which leads some clients to treat the domain in the link as a relative path:
```xml
<entry>
<title type="html">It’s Awards Season</title>
<link href="firesidefiction.com/its-awards-season-2017" rel="alternate" type="text/html" title="It's Awards Season"/>
```
so the feed client opens http://firesidefiction.com/firesidefiction.com/its-awards-season-2017 instead, which leads to a 404.

**Comment by luv2code** [comment]
I believe this can be fixed by adding `http://` to the url in _config.yml
https://github.com/firesidefiction/firesidefiction.github.io/blob/bee1a5cad08fd56e0ebecc1a0a120bcc314eff94/_config.yml#L21

**Comment by pablodefendini** [comment]
Fixed, thanks!

**Comment by luv2code** [comment]
:ok_hand: looks good on my end. fixed confirmed.
